### ISSUE TITLE
Problem in Auto weka

### ISSUE THREAD

**Issue by larimiguez** [dsibournemouth/autoweka#12]
Hi team !

I am facing some problem in running Auto Weka on my machine. Please, can you guys help me?

I get the following error:

java.lang.RuntimeException: Default not found in set in _0__wcfplsc_00_A_QUOTE_START_filter {} [weka.filters.supervised.attribute.PLSFilter]
	at autoweka.Parameter.<init>(Parameter.java:42)
	at autoweka.ClassParams.<init>(ClassParams.java:68)
	at autoweka.smac.SMACTrajectoryParser.parseTrajectory(SMACTrajectoryParser.java:34)
	at autoweka.TrajectoryParser.getTrajectory(TrajectoryParser.java:110)
	at autoweka.ui.TrainedModelRunner.openExperiment(TrainedModelRunner.java:137)
	at autoweka.ui.Wizard$1.update(Wizard.java:83)
	at autoweka.ui.ExperimentRunner$1.run(ExperimentRunner.java:125)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DraXus** [comment]
Hi @larimiguez,

I haven't seen this error before. Could you please provide more information about how are you running the software?
